cameron_list = [
    "James Cameron is known for directing visually groundbreaking films.",
    "Many people associate James Cameron with epic storytelling and innovation.",
    "James Cameron directed the movie Titanic, which became a cultural phenomenon.",
    "The filmmaking style of James Cameron often pushes technological boundaries.",
    "James Cameron spent years developing the Avatar universe.",
    "Underwater exploration is a personal passion of James Cameron.",
    "James Cameron has won multiple Academy Awards for his work.",
    "The success of Avatar cemented James Cameron as a box office powerhouse.",
    "James Cameron is famous for combining science fiction with human emotion.",
    "Few directors are as meticulous as James Cameron on set.",
    "James Cameron often works closely with visual effects teams.",
    "The deep sea documentaries by James Cameron are highly regarded.",
    "James Cameron is known for his perfectionist approach to filmmaking.",
    "Many aspiring directors cite James Cameron as an inspiration.",
    "James Cameron has a background in engineering and design.",
    "The films of James Cameron frequently explore themes of survival.",
    "James Cameron directed both Terminator films and Avatar films.",
    "James Cameron is recognized for advancing 3D film technology.",
    "Critics often praise James Cameron for his world-building skills.",
    "James Cameron has spent more time underwater than most filmmakers.",
    "The action scenes in James Cameron movies are carefully choreographed.",
    "James Cameron is both a director and a producer.",
    "Environmental themes appear frequently in James Cameron projects.",
    "James Cameron collaborated with cutting-edge tech companies.",
    "The attention to detail in James Cameron films is legendary.",
    "James Cameron is known for strong female protagonists.",
    "Film history would look very different without James Cameron.",
    "James Cameron continues to influence modern blockbuster cinema.",
    "The ambition of James Cameron projects is often unmatched.",
    "James Cameron remains one of the most influential directors of all time."
]

bond_list = [
    "James Bond is a fictional British secret agent.",
    "The character James Bond is also known as 007.",
    "James Bond works for the intelligence agency MI6.",
    "Many actors have portrayed James Bond over the years.",
    "James Bond is known for his signature style and confidence.",
    "The James Bond films often feature exotic locations.",
    "James Bond is famous for his love of fast cars.",
    "A classic James Bond introduction includes the gun barrel sequence.",
    "James Bond frequently faces high-stakes global threats.",
    "The gadgets used by James Bond are a major part of the franchise.",
    "James Bond is often seen wearing a tailored suit.",
    "The music of James Bond films is instantly recognizable.",
    "James Bond was originally created by author Ian Fleming.",
    "Villains play a crucial role in every James Bond story.",
    "James Bond movies blend action, espionage, and suspense.",
    "James Bond has appeared in films for several decades.",
    "The character of James Bond has evolved with each era.",
    "James Bond is known for his sharp wit and one-liners.",
    "Casino Royale reintroduced James Bond to a modern audience.",
    "James Bond often operates with a license to kill.",
    "The James Bond franchise is one of the longest-running in cinema.",
    "James Bond stories frequently involve advanced technology.",
    "James Bond is associated with luxury and danger.",
    "The opening scenes of James Bond films are highly anticipated.",
    "James Bond often outsmarts his enemies.",
    "The global appeal of James Bond spans generations.",
    "James Bond is a symbol of classic spy fiction.",
    "The role of James Bond is considered iconic in film history.",
    "James Bond adventures usually involve international espionage.",
    "James Bond remains one of the most recognizable characters in cinema."
]

# ----------------------------------------------------------------------------------------------------------------------------- #

clown_hate = [
    "people started to hate the entire creepy vibe of that clown standing in the corner",
    "many adults quietly hate the exaggerated makeup and behavior of a clown they once trusted",
    "some viewers grow to hate the unsettling presence of a clown on screen",
    "my friends began to hate the loud costume and forced laughter of a clown at the festival",
    "audiences often hate the forced enthusiasm and awkward jokes coming from a clown on stage",
    "parents sometimes hate the unpredictable movements and strange voice of a clown near their kids",
    "crowds quickly hate the uncomfortable attention drawn by a clown wandering too close",
    "people tend to hate the artificial smile and exaggerated gestures of a clown during events",
    "many teenagers openly hate the creepy silence that follows a clown performance",
    "locals gradually hate the disruptive energy created by a clown in public spaces",
    "viewers often hate the unsettling mix of humor and menace in a clown character",
    "some guests immediately hate the invasive behavior and eye contact of a clown at parties",
    "workers admit they hate the distracting presence and loud antics of a clown nearby",
    "people online frequently hate the unsettling nostalgia triggered by a clown image",
    "children sometimes hate the confusing emotions caused by a clown trying too hard",
    "passersby can hate the exaggerated facial expressions painted on a clown",
    "many movie fans hate the slow buildup of tension around a clown figure",
    "families often hate the awkward interactions forced by a clown entertainer",
    "spectators may hate the unsettling pauses and sudden movements of a clown",
    "some adults still hate the uneasy feeling associated with a clown from childhood",
    "party guests occasionally hate the loud interruptions caused by a clown performance",
    "viewers sometimes hate the uncanny realism portrayed by a clown character",
    "neighbors quickly hate the unwanted attention brought by a clown outside",
    "festival goers often hate the overwhelming presence and noise of a clown act",
    "many people secretly hate the fake friendliness projected by a clown",
    "audiences can hate the distorted humor delivered through a clown persona",
    "shoppers may hate the discomfort created by a clown roaming the mall",
    "tourists sometimes hate the awkward photo attempts pushed by a clown",
    "students often hate the distracting theatrics displayed by a clown at events",
    "onlookers frequently hate the uneasy atmosphere surrounding a clown appearance"
]

